macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  script: |
    brew install gcc@11 pyenv
    pyenv install 3.10.4
    export PATH="~/.pyenv/shims:${PATH}"
    pyenv local 3.10.4
    pip3 install meson build wheel twine
    CC=gcc-11 CXX=g++-11 python3 scripts/build_wheel.py

