[build-system]
requires = ["git+https://github.com/jeandet/mesonpep517@windows_fix_dump-pep425tags", "wheel", "ninja>=1.8.2", "meson<=0.61.4"]
build-backend = "mesonpep517.buildapi"


[tool.mesonpep517.metadata]
description="A modern C++ header only cdf library"
author = "Alexis Jeandet"
author-email = "alexis.jeandet@member.fsf.org"
summary = "A simple to use CDF files reader"
[project]
requires-python=">=3.7"
license = "GNU General Public License v3"
readme = "README.md"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
dependencies = ['numpy']
[project.urls]
homepage = "https://github.com/SciQLop/CDFpp"
