[build-system]
requires = ["mesonpep517"]
build-backend = "mesonpep517.buildapi"

[tool.mesonpep517]
build-backend = "mesonpep517.buildapi"

[tool.mesonpep517.metadata]
author="Alexis Jeandet"
author-email="alexis.jeandet@member.fsf.org"
summary="A modern C++ header only cdf library"
home-page="https://github.com/SciQLop/CDFpp"
requires-python="py3"
description-file="README.md"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
]

