name: C/C++ CI

on: [push]

jobs:
  build:
    name: build an tests
    runs-on: ubuntu-latest
    container: jeandet/simple_cxx_fedora
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Configure with CMake
        run: cmake -S . -B build_cmake
      - name: Build
        run: cmake --build build_cmake
      - name: Build
        run: cd build_cmake && ctest && cd ..
      - name: Configure with meson
        run: meson . build
      - name: Build
        run: ninja -C build
      - name: Build
        run: ninja test -C build
