name: C/C++ CI

on: [push]

jobs:
  build:
    name: build an tests
    runs-on: ubuntu-latest
    container: jeandet/simple_cxx_fedora
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Configure with CMake
        run: cmake -S . -B build_cmake
      - name: Build (CMake)
        run: cmake --build build_cmake
      - name: Run tests (CMake)
        run: cd build_cmake && ctest && cd ..
      - name: Configure with meson
        run: meson -Db_coverage=true . build
      - name: Build (meson)
        run: ninja -C build
      - name: Run tests (meson)
        run: ninja test -C build
      - name: Generate Coverage repport
        run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.info
          flags: unittests
          name: codecov-cdfpp
          yml: ./codecov.yml
          fail_ci_if_error: true
