name: Tests Linux with coverage

on: [push]

jobs:
  build:
    name: build an tests with coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-dev lcov g++ catch2
          pip install --upgrade meson ninja numpy meson-python>=0.14.0 build wheel ddt requests
      - name: Configure with meson
        run: meson -Db_coverage=true -Dwith_tests=true . build
      - name: Build (meson)
        run: ninja -C build
      - name: Run tests (meson)
        run: ninja test -C build
      - name: Generate Coverage report
        run: |
          lcov --capture --ignore-errors=inconsistent,mismatch --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --ignore-errors=unused --output-file coverage.info
          lcov --remove coverage.info '*/catch*' --ignore-errors=unused --output-file coverage.info
          lcov --list coverage.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.info
          flags: unittests
          name: codecov-cdfpp
          yml: ./codecov.yml
          fail_ci_if_error: true
