name: All OS test matrix

on: [push]

jobs:
  build:
    name: All OS test matrix
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v1
      - name: Build python wheel
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: build and test (OSX)
        if: matrix.os == 'macos-latest'
        run: |
          pip install --upgrade meson ninja numpy
          CC=gcc-11 CXX=g++-11 meson -Dbuildtype=release -Dwith_tests=true . build
          ninja --verbose -C build
          ninja test -C build
      - name: build and test (Linux/Windows)
        if: matrix.os != 'macos-latest'
        run: |
          pip install --upgrade meson ninja numpy
          meson -Dbuildtype=release -Dwith_tests=true . build
          ninja --verbose -C build
          ninja test -C build
